### ISSUE TITLE
Горизонтальные форматы и А3

### ISSUE THREAD

**Issue by VitaliyAT** [baranovskiykonstantin/eskd-templates#2]
1. Замечательный проект. Спасибо вам. Прям то что искал.
2. Не хватает горизонтальных рамок и рамок А3 (горизонтальных - в первую очередь именно их так как подшиваются в альбом А4 свернувшись пополам)

**Comment by VitaliyAT** [comment]
![10001E61000052220000741EDA0F5E82E99FFB4B_A3](https://github.com/baranovskiykonstantin/eskd-templates/assets/1639608/8f85e02c-8dac-42c3-a7e4-21a64fc5ee74)
я начал копаться в проекте и понимаю примерно, что вы в качестве подложки стиля закидываете векторный рисунок (в теории) и потом раскидываете текстовые поля... расширил рамку второго листа до горизонтального А3 (как в помощь вам) используя привязку по миллиметровой сетке и склонировав (а не скопировав, вдруг это важно) недостающую линию.

**Comment by baranovskiykonstantin** [comment]
Можно добавить горизонтальный формат А3 для стиля страниц пояснительной записки. В остальных документах форматы чётко прописаны в стандартах.

**Comment by VitaliyAT** [comment]
По сути только это и надо (мне)
